apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: myapp
        image: ganeshkarthik/myapp:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: nodeapp
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 31110
